name: islamic_app
description: A new Flutter application.


publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #ui_enhancment
  animated_bottom_navigation_bar: ^0.3.2
  buildcondition: ^0.0.4
  circular_reveal_animation: ^2.0.0

  #bloc
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  #service
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  hive: ^2.0.5
  #utils
  intl: ^0.17.0
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  flutter_offline: ^2.1.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.0.3
  #fetuers
  quran: ^1.1.1
  flutter_qiblah: ^2.0.2
  geolocator: ^7.6.0








dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/images/


  # example:
  fonts:
    - family: AdvertisingBold
      fonts:
        - asset: assets/fonts/AdvertisingBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
